### ISSUE TITLE
Vault auth problem in k8s 1.21

### ISSUE THREAD

**Issue by herzogf** [jkayani/avp-demo-kubecon-2021#1]
Thanks for your great demo at kubecon 2021 NA!

I tried to replicate this on a kind cluster with k8s v1.21 and failed because Argo CD / the argo vault plugin throws the following exception:

```
rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: Error making API request. URL: PUT http://vault:8200/v1/auth/kubernetes/login Code: 500. Errors: * claim "iss" is invalid Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD)
```

In the end this seems to be a combination of vault and kubernetes 1.21 - I stumbled upon the following issue and its "insecure" workaround fixes the demo for me: https://github.com/external-secrets/kubernetes-external-secrets/issues/721#issue-868030068

I changed this line https://github.com/jkayani/avp-demo-kubecon-2021/blob/main/vault/app.yaml#L34 from
```
vault write auth/kubernetes/config kubernetes_host=https://kubernetes.docker.internal:6443 &&\
```
to
```
vault write auth/kubernetes/config kubernetes_host=https://kubernetes.default.svc disable_iss_validation=true &&\
```
and the argo vault plugin could finally authenticate with vault.

Just a FYI for all: I applied all demo commands in the `default` namespace and thus argo also came out in this namespace. I had to fix the 2 clusterrolebindings for argocd as they pointed to a serviceaccount in the "argocd" namespace.

**Comment by jkayani** [comment]
Thanks @herzogf - you're right. I tried to fix it the "proper" way by telling Vault who the issuer is supposed to be (for my local cluster, just `https://kubernetes.default.svc`) but that didn't seem to work 🤷 . Perhaps I still wasn't doing it correctly. Anyway, your suggestion works like a charm - thanks again for sharing!
